### ISSUE TITLE
Typecho：评论无回复按钮

### ISSUE THREAD

**Issue by YangMame** [Kilerd/Cat#4]
应该在comments.php加上 `<?php $comments->reply(); ?>`

https://github.com/YangMame/Cat/commit/e8194cb33400369ef58e6db72a11eeac0e8bdd2e

**Comment by Kilerd** [comment]
多谢反馈，如果你fork出去修改完之后，可以提一个PR。

**Comment by YangMame** [comment]
已经fork了。。但是为了方便使用我删掉了非typecho主题的代码。。所以还是你来吧 (最好能优化下评论的样式？其实我不懂PHP  2333  @Kilerd

**Comment by Kilerd** [comment]
OK，我会修复的。
BTW，你指的评论样式的问题？ 是UI不好看？ 还是出现了功能的缺失？
如果是UI不好看，可以给出期望的类似设计吗？ 毕竟这个主题走的是简约的风格。

**Comment by YangMame** [comment]
你可以看看我的博客 ：https://blog.yangmame.org 默认是辣眼的蓝色+下划线 我觉得应该改成和首页文章页面点按一样的背景变暗不过字体颜色可以不一样（口胡

**Comment by Kilerd** [comment]
so sorry for the late responding.

你可以在 style.css 中加入一下代码来指定「回复」的样式
```css
ol.comment-list li.comment>a {
    color: #444443;
    text-decoration: underline;
}
ol.comment-list li.comment>a {
    color: #444443;
    text-decoration: none;
}
```
